//export * from "./model/model";
//export * from "./model/meta";
//export * from "./match/ifmatch";
import * as ErBase from "./match/erbase";
export { ErBase };
import * as Sentence from "./match/sentence";
export { Sentence };
import * as InputFilterRules from "./match/inputFilterRules";
export { InputFilterRules };
import * as InputFilter from "./match/inputFilterRules";
export { InputFilter };
import * as Word from "./match/word";
export { Word };
import * as IFErBase from "./match/iferbase";
